//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.18 at 03:17:14 PM EET 
//


package generatedsoapclasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generatedsoapclasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generatedsoapclasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateSubscriberRequest }
     * 
     */
    public UpdateSubscriberRequest createUpdateSubscriberRequest() {
        return new UpdateSubscriberRequest();
    }

    /**
     * Create an instance of {@link Subscriber }
     * 
     */
    public Subscriber createSubscriber() {
        return new Subscriber();
    }

    /**
     * Create an instance of {@link DeleteSubscriberResponse }
     * 
     */
    public DeleteSubscriberResponse createDeleteSubscriberResponse() {
        return new DeleteSubscriberResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link GetSubscriberResponse }
     * 
     */
    public GetSubscriberResponse createGetSubscriberResponse() {
        return new GetSubscriberResponse();
    }

    /**
     * Create an instance of {@link AddSubscriberResponse }
     * 
     */
    public AddSubscriberResponse createAddSubscriberResponse() {
        return new AddSubscriberResponse();
    }

    /**
     * Create an instance of {@link GetSubscribersResponse }
     * 
     */
    public GetSubscribersResponse createGetSubscribersResponse() {
        return new GetSubscribersResponse();
    }

    /**
     * Create an instance of {@link UpdateSubscriberResponse }
     * 
     */
    public UpdateSubscriberResponse createUpdateSubscriberResponse() {
        return new UpdateSubscriberResponse();
    }

    /**
     * Create an instance of {@link GetSubscriberRequest }
     * 
     */
    public GetSubscriberRequest createGetSubscriberRequest() {
        return new GetSubscriberRequest();
    }

    /**
     * Create an instance of {@link GetSubscribersRequest }
     * 
     */
    public GetSubscribersRequest createGetSubscribersRequest() {
        return new GetSubscribersRequest();
    }

    /**
     * Create an instance of {@link DeleteSubscriberRequest }
     * 
     */
    public DeleteSubscriberRequest createDeleteSubscriberRequest() {
        return new DeleteSubscriberRequest();
    }

    /**
     * Create an instance of {@link AddSubscriberRequest }
     * 
     */
    public AddSubscriberRequest createAddSubscriberRequest() {
        return new AddSubscriberRequest();
    }

}
